/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import controlador.ControladorIniciarSesion;
import modelo.UsuariosVO;
import Controlador.ControladorPrincipal;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author John
 */
public class JFIniciarSesion extends javax.swing.JFrame {

      ControladorIniciarSesion ControlInicio;
      JFPrincipal principal;
     
      public String tipo;
      public int Id;
     
    /**
     * Creates new form IniciarSesionView
     */
    public JFIniciarSesion() {
        this.setType(Type.NORMAL);
        initComponents();

        configuracionInicial();
    }

    private void configuracionInicial() {
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        URL rutaIcono = this.getClass().getClassLoader().getResource("Imagenes/misiontic.png");
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.createImage(rutaIcono);
        this.setIconImage(img);
        
        this.setTitle("Inicio de Sesión | MisionTic");
        //btniniciar.setCursor(Cursor.getPredefinedCursor(HAND_CURSOR));

        lblmensaje1.setText(" ");
        lblmensaje2.setText(" ");

        jToolBar1.setBackground(Color.white);
        jpfondo.setBackground(Color.white);
    }
    
     
    

    private void iniciarSesion() throws SQLException {
        ControlInicio = new ControladorIniciarSesion();
        UsuariosVO usuariovo = new UsuariosVO();
   
         char[] passw = txtcontrasena.getPassword();
                String passw1 = new String(passw);
              
        usuariovo.setNick(txtnombreusuario.getText());
        usuariovo.setPasswd(passw1);
        usuariovo.setIdEstado(1);

        if (ControlInicio.iniciarSesion(usuariovo)) {
            tipo = usuariovo.getTipUser();
            Id = usuariovo.getIdUser();
            principal = new JFPrincipal();
          
            if (usuariovo.getTipUser().trim().equals("Administrador")) {
             
              principal.lblusuarios.setText(usuariovo.getNombre());
              principal.lbltipo.setText("Administrador");
              principal.lbltipo.setVisible(false);
              principal.lblId.setText(String.valueOf(Id));
              principal.lblId.setVisible(false);
                
            } else {
                
              
                principal.lblusuarios.setText(usuariovo.getNombre());
                 principal.lbltipo.setText("Usuario");
              principal.lbltipo.setVisible(false);
              principal.lblId.setText(String.valueOf(Id));
              principal.lblId.setVisible(false);
               
            }
            this.dispose();
          
       ControladorPrincipal controlador = new ControladorPrincipal(principal);
       principal.setVisible(true);
       if ("Calidad".equals(usuariovo.getNick())){
                    
                    JOptionPane.showMessageDialog(principal.jdpescritorio, "Bienvenido Usuario de Alto Nivel \n Estamos mejorando para cumplir sus expectativas!!"); 
                
            }

        }

        lblmensaje1.setForeground(Color.red);
        lblmensaje2.setForeground(Color.red);
        lblmensaje1.setText(ControlInicio.mensaje1);
        lblmensaje2.setText(ControlInicio.mensaje2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpfondo = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        txtnombreusuario = new javax.swing.JTextField();
        lblPasswd = new javax.swing.JLabel();
        txtcontrasena = new javax.swing.JPasswordField();
        btniniciar = new javax.swing.JButton();
        lblmensaje1 = new javax.swing.JLabel();
        lblmensaje2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUser.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblUser.setText("Nombre de usuario");

        txtnombreusuario.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtnombreusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreusuarioActionPerformed(evt);
            }
        });
        txtnombreusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnombreusuarioKeyPressed(evt);
            }
        });

        lblPasswd.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblPasswd.setText("Contraseña");

        txtcontrasena.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtcontrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontrasenaActionPerformed(evt);
            }
        });
        txtcontrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcontrasenaKeyPressed(evt);
            }
        });

        btniniciar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btniniciar.setText("Iniciar Sesión");
        btniniciar.setContentAreaFilled(false);
        btniniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btniniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btniniciarMouseExited(evt);
            }
        });
        btniniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniniciarActionPerformed(evt);
            }
        });

        lblmensaje1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblmensaje1.setText(" ");

        lblmensaje2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblmensaje2.setText(" ");

        jToolBar1.setRollover(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/misiontic.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jpfondoLayout = new javax.swing.GroupLayout(jpfondo);
        jpfondo.setLayout(jpfondoLayout);
        jpfondoLayout.setHorizontalGroup(
            jpfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpfondoLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(jpfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPasswd)
                    .addComponent(lblUser)
                    .addComponent(txtcontrasena)
                    .addComponent(txtnombreusuario)
                    .addComponent(lblmensaje1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblmensaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btniniciar))
                .addGap(18, 18, 18)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jpfondoLayout.setVerticalGroup(
            jpfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpfondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnombreusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPasswd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btniniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblmensaje1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblmensaje2)
                .addGap(38, 38, 38))
            .addGroup(jpfondoLayout.createSequentialGroup()
                .addGroup(jpfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpfondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpfondoLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jpfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btniniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniniciarActionPerformed
          try {
              iniciarSesion();
          } catch (SQLException ex) {
              Logger.getLogger(JFIniciarSesion.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_btniniciarActionPerformed

    private void btniniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btniniciarMouseEntered
        btniniciar.setContentAreaFilled(true);
    }//GEN-LAST:event_btniniciarMouseEntered

    private void btniniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btniniciarMouseExited
        btniniciar.setContentAreaFilled(false);
    }//GEN-LAST:event_btniniciarMouseExited

    private void txtnombreusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreusuarioActionPerformed

        if (!txtnombreusuario.getText().trim().equals("")) {
            txtnombreusuario.transferFocus();
            try {
                iniciarSesion();
            } catch (SQLException ex) {
                Logger.getLogger(JFIniciarSesion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtnombreusuarioActionPerformed

    private void txtcontrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontrasenaActionPerformed

        if (!txtcontrasena.getPassword().equals("")) {
            txtcontrasena.transferFocus();
            try {
                iniciarSesion();
            } catch (SQLException ex) {
                Logger.getLogger(JFIniciarSesion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtcontrasenaActionPerformed

    private void txtnombreusuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreusuarioKeyPressed

    }//GEN-LAST:event_txtnombreusuarioKeyPressed

    private void txtcontrasenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontrasenaKeyPressed

    }//GEN-LAST:event_txtcontrasenaKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btniniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel jpfondo;
    private javax.swing.JLabel lblPasswd;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblmensaje1;
    private javax.swing.JLabel lblmensaje2;
    private javax.swing.JPasswordField txtcontrasena;
    private javax.swing.JTextField txtnombreusuario;
    // End of variables declaration//GEN-END:variables
}
