/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Controlador.ControladorImagenPanel;
import modelo.Splash;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

/**
 *
 * @author JuanGui
 */
public class JFVentanaSplash extends javax.swing.JFrame implements Runnable {

    JFIniciarSesion inicioSesion = new JFIniciarSesion();
    JFPrincipal principalview;
   
    /**
     * Creates new form VentanaSplashView
     */
    public JFVentanaSplash() {
        this.setUndecorated(true);
        initComponents();
        configuracionInicial();
    }
    
    private void configuracionInicial() {
        this.setLocationRelativeTo(null);
        
        URL rutaIcono = this.getClass().getClassLoader().getResource("Imagenes/misiontic.png");
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.createImage(rutaIcono);
        this.setIconImage(img);
        
        this.setTitle("Iniciando Aplicación");
        
        ControladorImagenPanel controlImagen = new ControladorImagenPanel("/Imagenes/misiontic_1.png", 660, 300);
        jpimagen.add(controlImagen);
        jpimagen.repaint();        
        //jpimagen.setCursor(Cursor.getPredefinedCursor(WAIT_CURSOR));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpimagen = new javax.swing.JPanel();
        jprogreso = new javax.swing.JProgressBar();
        etimensaje = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jpimagen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        etimensaje.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        etimensaje.setForeground(new java.awt.Color(51, 51, 51));
        etimensaje.setText(" ");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("V 1.0");

        javax.swing.GroupLayout jpimagenLayout = new javax.swing.GroupLayout(jpimagen);
        jpimagen.setLayout(jpimagenLayout);
        jpimagenLayout.setHorizontalGroup(
            jpimagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jprogreso, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpimagenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etimensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jpimagenLayout.setVerticalGroup(
            jpimagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpimagenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpimagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etimensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                .addComponent(jprogreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpimagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpimagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        new Splash(jprogreso, etimensaje).start();
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etimensaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpimagen;
    private javax.swing.JProgressBar jprogreso;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        try {
            this.setVisible(true);
            Thread.sleep(6000);
            this.dispose();            
            inicioSesion.setVisible(true);
             //principalview = new JFPrincipal();
             //ControladorPrincipal controlador = new ControladorPrincipal(principalview);
       //principalview.setVisible(true);
            
        } catch(InterruptedException e) {
            System.out.println("Error interfaz\n" + e + "\n" + e.getMessage() + "\n" + e.getCause());
        }
    }
}
